name: flutter_weather
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  ### flutter_weather_app dependencies ###
  # Future-based library for making HTTP requests.
  http: ^0.12.0+2
  # This package provides date/number formatting and parsing.
  intl: ^0.16.0
  # Handles getting location on Android and iOS.
  # location: ^2.3.5
  location: "^1.3.4"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
